create index os_memberships_user_id_idx on public.os_memberships (user_id);
create index os_memberships_organization_role_idx on public.os_memberships (organization_id, role);
create index os_locations_organization_id_idx on public.os_locations (organization_id);
create index os_departments_organization_id_idx on public.os_departments (organization_id);
create index os_departments_location_id_idx on public.os_departments (location_id);
create index os_stations_organization_id_idx on public.os_stations (organization_id);
create index os_stations_location_id_idx on public.os_stations (location_id);
create index os_stations_department_id_idx on public.os_stations (department_id);
create index os_roles_organization_id_idx on public.os_roles (organization_id);
create index os_processes_organization_id_idx on public.os_processes (organization_id);
create index os_processes_department_id_idx on public.os_processes (department_id);
create index os_processes_owner_role_id_idx on public.os_processes (owner_role_id);
create index os_processes_active_idx on public.os_processes (organization_id, code) where status = 'active';
create index os_source_manuals_organization_id_idx on public.os_source_manuals (organization_id);
create index os_source_sections_organization_id_idx on public.os_source_sections (organization_id);
create index os_source_sections_manual_id_idx on public.os_source_sections (manual_id);
create index os_canonical_knowledge_organization_id_idx on public.os_canonical_knowledge (organization_id);
create index os_canonical_knowledge_current_approved_version_id_idx on public.os_canonical_knowledge (current_approved_version_id) where current_approved_version_id is not null;
create index os_knowledge_versions_organization_id_idx on public.os_knowledge_versions (organization_id);
create index os_knowledge_versions_knowledge_id_idx on public.os_knowledge_versions (knowledge_id);
create index os_knowledge_versions_approved_idx on public.os_knowledge_versions (knowledge_id, version_number desc) where status = 'approved';
create index os_sops_organization_id_idx on public.os_sops (organization_id);
create index os_sops_process_id_idx on public.os_sops (process_id);
create index os_sops_canonical_knowledge_id_idx on public.os_sops (canonical_knowledge_id);
create index os_sops_owner_role_id_idx on public.os_sops (owner_role_id);
create index os_checklists_organization_id_idx on public.os_checklists (organization_id);
create index os_checklists_process_id_idx on public.os_checklists (process_id);
create index os_checklists_sop_id_idx on public.os_checklists (sop_id);
create index os_checklists_station_id_idx on public.os_checklists (station_id);
create index os_checklist_items_organization_id_idx on public.os_checklist_items (organization_id);
create index os_checklist_items_checklist_id_idx on public.os_checklist_items (checklist_id);
create index os_training_paths_organization_id_idx on public.os_training_paths (organization_id);
create index os_training_paths_role_id_idx on public.os_training_paths (role_id);
create index os_lessons_organization_id_idx on public.os_lessons (organization_id);
create index os_lessons_canonical_knowledge_id_idx on public.os_lessons (canonical_knowledge_id);
create index os_training_path_lessons_organization_id_idx on public.os_training_path_lessons (organization_id);
create index os_training_path_lessons_training_path_id_idx on public.os_training_path_lessons (training_path_id);
create index os_training_path_lessons_lesson_id_idx on public.os_training_path_lessons (lesson_id);
create index os_quizzes_organization_id_idx on public.os_quizzes (organization_id);
create index os_quizzes_lesson_id_idx on public.os_quizzes (lesson_id);
create index os_quiz_questions_organization_id_idx on public.os_quiz_questions (organization_id);
create index os_quiz_questions_quiz_id_idx on public.os_quiz_questions (quiz_id);
create index os_certifications_organization_id_idx on public.os_certifications (organization_id);
create index os_certifications_user_id_idx on public.os_certifications (user_id);
create index os_certifications_role_id_idx on public.os_certifications (role_id);
create index os_certifications_training_path_id_idx on public.os_certifications (training_path_id);
create index os_certifications_active_user_idx on public.os_certifications (organization_id, user_id, expires_at) where status = 'active';
create index os_audits_organization_id_idx on public.os_audits (organization_id);
create index os_audits_location_id_idx on public.os_audits (location_id);
create index os_audits_checklist_id_idx on public.os_audits (checklist_id);
create index os_audits_auditor_id_idx on public.os_audits (auditor_id);
create index os_audit_findings_organization_id_idx on public.os_audit_findings (organization_id);
create index os_audit_findings_audit_id_idx on public.os_audit_findings (audit_id);
create index os_audit_findings_checklist_item_id_idx on public.os_audit_findings (checklist_item_id);
create index os_incidents_organization_id_idx on public.os_incidents (organization_id);
create index os_incidents_location_id_idx on public.os_incidents (location_id);
create index os_incidents_station_id_idx on public.os_incidents (station_id);
create index os_incidents_process_id_idx on public.os_incidents (process_id);
create index os_incidents_open_idx on public.os_incidents (organization_id, severity, created_at desc) where status in ('open', 'investigating');
create index os_ai_agents_organization_id_idx on public.os_ai_agents (organization_id);
create index os_approvals_organization_id_idx on public.os_approvals (organization_id);
create index os_approvals_object_idx on public.os_approvals (object_type, object_id);
create index os_approvals_requested_idx on public.os_approvals (organization_id, created_at) where status = 'requested';
create index os_evidence_links_organization_id_idx on public.os_evidence_links (organization_id);
create index os_evidence_links_object_idx on public.os_evidence_links (object_type, object_id);
create index os_evidence_links_source_section_id_idx on public.os_evidence_links (source_section_id);
create index os_coverage_items_organization_id_idx on public.os_coverage_items (organization_id);
create index os_coverage_items_object_idx on public.os_coverage_items (object_type, object_id);
create index os_coverage_items_status_idx on public.os_coverage_items (organization_id, status);
