alter table public.os_organizations enable row level security;
alter table public.os_memberships enable row level security;
alter table public.os_locations enable row level security;
alter table public.os_departments enable row level security;
alter table public.os_stations enable row level security;
alter table public.os_roles enable row level security;
alter table public.os_processes enable row level security;
alter table public.os_source_manuals enable row level security;
alter table public.os_source_sections enable row level security;
alter table public.os_canonical_knowledge enable row level security;
alter table public.os_knowledge_versions enable row level security;
alter table public.os_sops enable row level security;
alter table public.os_checklists enable row level security;
alter table public.os_checklist_items enable row level security;
alter table public.os_training_paths enable row level security;
alter table public.os_lessons enable row level security;
alter table public.os_training_path_lessons enable row level security;
alter table public.os_quizzes enable row level security;
alter table public.os_quiz_questions enable row level security;
alter table public.os_certifications enable row level security;
alter table public.os_audits enable row level security;
alter table public.os_audit_findings enable row level security;
alter table public.os_incidents enable row level security;
alter table public.os_ai_agents enable row level security;
alter table public.os_approvals enable row level security;
alter table public.os_evidence_links enable row level security;
alter table public.os_coverage_items enable row level security;

create policy os_organizations_member_select on public.os_organizations for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_organizations.id and m.user_id = (select auth.uid())));
create policy os_memberships_self_select on public.os_memberships for select to authenticated using (user_id = (select auth.uid()));

create policy os_locations_member_select on public.os_locations for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_locations.organization_id and m.user_id = (select auth.uid())));
create policy os_locations_manager_write on public.os_locations for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_locations.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_locations.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager')));

create policy os_departments_member_select on public.os_departments for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_departments.organization_id and m.user_id = (select auth.uid())));
create policy os_departments_manager_write on public.os_departments for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_departments.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_departments.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager')));

create policy os_stations_member_select on public.os_stations for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_stations.organization_id and m.user_id = (select auth.uid())));
create policy os_stations_manager_write on public.os_stations for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_stations.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_stations.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager')));

create policy os_roles_member_select on public.os_roles for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_roles.organization_id and m.user_id = (select auth.uid())));
create policy os_roles_manager_write on public.os_roles for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_roles.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_roles.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager')));

create policy os_processes_member_select on public.os_processes for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_processes.organization_id and m.user_id = (select auth.uid())));
create policy os_processes_manager_write on public.os_processes for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_processes.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_processes.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager')));

create policy os_source_manuals_member_select on public.os_source_manuals for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_source_manuals.organization_id and m.user_id = (select auth.uid())));
create policy os_source_manuals_manager_insert on public.os_source_manuals for insert to authenticated with check (exists (select 1 from public.os_memberships m where m.organization_id = os_source_manuals.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager')));
create policy os_source_sections_member_select on public.os_source_sections for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_source_sections.organization_id and m.user_id = (select auth.uid())));
create policy os_source_sections_manager_insert on public.os_source_sections for insert to authenticated with check (exists (select 1 from public.os_memberships m where m.organization_id = os_source_sections.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager')));

create policy os_canonical_knowledge_member_select on public.os_canonical_knowledge for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_canonical_knowledge.organization_id and m.user_id = (select auth.uid())));
create policy os_canonical_knowledge_trainer_write on public.os_canonical_knowledge for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_canonical_knowledge.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_canonical_knowledge.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));
create policy os_knowledge_versions_member_select on public.os_knowledge_versions for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_knowledge_versions.organization_id and m.user_id = (select auth.uid())));
create policy os_knowledge_versions_trainer_write on public.os_knowledge_versions for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_knowledge_versions.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_knowledge_versions.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));

create policy os_sops_member_select on public.os_sops for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_sops.organization_id and m.user_id = (select auth.uid())));
create policy os_sops_trainer_write on public.os_sops for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_sops.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_sops.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));
create policy os_checklists_member_select on public.os_checklists for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_checklists.organization_id and m.user_id = (select auth.uid())));
create policy os_checklists_trainer_write on public.os_checklists for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_checklists.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_checklists.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));
create policy os_checklist_items_member_select on public.os_checklist_items for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_checklist_items.organization_id and m.user_id = (select auth.uid())));
create policy os_checklist_items_trainer_write on public.os_checklist_items for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_checklist_items.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_checklist_items.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));

create policy os_training_paths_member_select on public.os_training_paths for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_training_paths.organization_id and m.user_id = (select auth.uid())));
create policy os_training_paths_trainer_write on public.os_training_paths for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_training_paths.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_training_paths.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));
create policy os_lessons_member_select on public.os_lessons for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_lessons.organization_id and m.user_id = (select auth.uid())));
create policy os_lessons_trainer_write on public.os_lessons for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_lessons.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_lessons.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));
create policy os_training_path_lessons_member_select on public.os_training_path_lessons for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_training_path_lessons.organization_id and m.user_id = (select auth.uid())));
create policy os_training_path_lessons_trainer_write on public.os_training_path_lessons for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_training_path_lessons.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_training_path_lessons.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));
create policy os_quizzes_member_select on public.os_quizzes for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_quizzes.organization_id and m.user_id = (select auth.uid())));
create policy os_quizzes_trainer_write on public.os_quizzes for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_quizzes.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_quizzes.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));
create policy os_quiz_questions_member_select on public.os_quiz_questions for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_quiz_questions.organization_id and m.user_id = (select auth.uid())));
create policy os_quiz_questions_trainer_write on public.os_quiz_questions for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_quiz_questions.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_quiz_questions.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));

create policy os_certifications_member_select on public.os_certifications for select to authenticated using (user_id = (select auth.uid()) or exists (select 1 from public.os_memberships m where m.organization_id = os_certifications.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer', 'auditor')));
create policy os_certifications_trainer_write on public.os_certifications for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_certifications.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_certifications.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer')));
create policy os_audits_member_select on public.os_audits for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_audits.organization_id and m.user_id = (select auth.uid())));
create policy os_audits_auditor_write on public.os_audits for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_audits.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'auditor'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_audits.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'auditor')));
create policy os_audit_findings_member_select on public.os_audit_findings for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_audit_findings.organization_id and m.user_id = (select auth.uid())));
create policy os_audit_findings_auditor_write on public.os_audit_findings for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_audit_findings.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'auditor'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_audit_findings.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'auditor')));

create policy os_incidents_member_select on public.os_incidents for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_incidents.organization_id and m.user_id = (select auth.uid())));
create policy os_incidents_member_insert on public.os_incidents for insert to authenticated with check (exists (select 1 from public.os_memberships m where m.organization_id = os_incidents.organization_id and m.user_id = (select auth.uid())));
create policy os_incidents_manager_update on public.os_incidents for update to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_incidents.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'auditor'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_incidents.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'auditor')));

create policy os_ai_agents_member_select on public.os_ai_agents for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_ai_agents.organization_id and m.user_id = (select auth.uid())));
create policy os_ai_agents_admin_write on public.os_ai_agents for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_ai_agents.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_ai_agents.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin')));
create policy os_approvals_member_select on public.os_approvals for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_approvals.organization_id and m.user_id = (select auth.uid())));
create policy os_approvals_manager_write on public.os_approvals for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_approvals.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_approvals.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager')));
create policy os_evidence_links_member_select on public.os_evidence_links for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_evidence_links.organization_id and m.user_id = (select auth.uid())));
create policy os_evidence_links_manager_write on public.os_evidence_links for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_evidence_links.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer', 'auditor'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_evidence_links.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer', 'auditor')));
create policy os_coverage_items_member_select on public.os_coverage_items for select to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_coverage_items.organization_id and m.user_id = (select auth.uid())));
create policy os_coverage_items_manager_write on public.os_coverage_items for all to authenticated using (exists (select 1 from public.os_memberships m where m.organization_id = os_coverage_items.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer', 'auditor'))) with check (exists (select 1 from public.os_memberships m where m.organization_id = os_coverage_items.organization_id and m.user_id = (select auth.uid()) and m.role in ('owner', 'admin', 'manager', 'trainer', 'auditor')));
